network/urls.py
from django.urls import path
from django.http import HttpResponse
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from . import views

app_name='network'


urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new_post/", views.new_post, name="new_post"),
    path('favicon.ico/', RedirectView.as_view(url='/static/img/favicon.ico', permanent = True)),
    path('editform/<int:id>/', views.editform, name='editform'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/', views.follow, name='follow'),
    path('unfollow/', views.unfollow, name='unfollow,'),
    path('following/', views.following, name='following'),
    path('like/', views.like, name='like'),
    path('unlike/', views.unlike, name='unlike')
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Posts(models.Model):
    username = models.CharField(max_length=25, null=True)
    content = models.TextField(null=True)
    timestamp = models.DateTimeField(null=True)
    likes = models.IntegerField(null=True)
    dislikes = models.IntegerField(null=True)
    last_edit = models.DateTimeField(null=True)

class Connections(models.Model):
    username = models.CharField(max_length=25, null=True)
    followed_by = models.CharField(max_length=25, null=True)


class Likes(models.Model):
    post_id = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='post_likes')
    follower = models.CharField(max_length=25, null=True)

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import datetime
import json
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from csp.decorators import csp_exempt

from .models import User, Posts, Connections

@csp_exempt
def index(request):
    if request.method == 'GET':
        wallet = request.GET.get('page', 1)
        #print(wallet)
        post_list = Posts.objects.all().order_by('-timestamp')
        p = Paginator(post_list, 10)
        page_obj = p.get_page(wallet)
        page_obj_test = p.get_page(13)
        #print(list(page_obj_test))
        # nums = page_obj.paginator.num_pages
        # print(nums)
        user = request.user.username

        

        try:
            paginated_argument = p.page(wallet)
        except PageNotAnInteger:
            paginated_argument = p.page(1)
        except EmptyPage:
            paginated_argument = p.page(p.num_pages)


        return render(request, "network/index.html", {
                "posts":post_list,
                "get_check": "True",
                "user_check": user,
                "page_obj":paginated_argument,
                # "nums":nums
            })
    else:
        post_list = Posts.objects.all().order_by('-timestamp')
        posts = serializers.serialize('json', list(post_list), fields=('username','content','timestamp','likes','dislikes'))
        return JsonResponse(posts, safe=False)
        
@csp_exempt
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")

@csp_exempt
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))

@csp_exempt
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

@csp_exempt
@login_required(login_url='/login')
def new_post(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print(data["body"])
        timestamp = datetime.datetime.now()
        post_save = Posts(username = request.user.username, content= data["body"], timestamp=timestamp)
        post_save.save()
        return JsonResponse({"message":"Post saved"})
    

@csp_exempt
@login_required(login_url='/login')
def editform(request, id):
    if request.method == 'PUT':
        data = json.loads(request.body)
        body = data["body"]
        timestamp = datetime.datetime.now()
        post_update = Posts.objects.get(id=id)
        post_update.content = body
        post_update.last_edit = timestamp
        post_update.save()

        context = dict()
        context["data"] = body
        context["timestamp"] = timestamp

        return JsonResponse({"data":body, "timestamp":timestamp, "id":id})


@csp_exempt
def profile(request, username):
    user = request.user.username
    user_posts = list(Posts.objects.filter(username=username).order_by('-timestamp'))
    check_con = list(Connections.objects.filter(username=username).filter(followed_by=user))
    follower_count = list(Connections.objects.filter(username=username))
    following_count = list(Connections.objects.filter(followed_by=username))
    con_status = ""
    if len(check_con) >= 1:
        con_status = "0"
    return render(request, "network/profile.html", {
        "username": username,
        "user_posts": user_posts,
        "user_check":user,
        "con_status":con_status,
        "follower_count": len(follower_count),
        "following_count":len(following_count)
    })


@csp_exempt
@login_required(login_url='/login')
def follow(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print(data['body'])
        follower = data['body']
        user = request.user.username
        connect_save = Connections(username = follower, followed_by = user)
        connect_save.save()
        follower_count = list(Connections.objects.filter(username=follower))
        return JsonResponse({'follower_count': follower_count})

@csp_exempt
@login_required(login_url='/login')
def unfollow(request):
    if request.method == 'DELETE':
        data = json.loads(request.body)
        tounfollow = data['body']
        print(data['body'])
        user = request.user.username
        connect_delete = Connections.objects.get(username = tounfollow, followed_by = user)
        connect_delete.delete()
        follower_count = list(Connections.objects.filter(username=tounfollow))
        return JsonResponse({"message": "success"})


@csp_exempt
@login_required(login_url='/login')
def following(request):
    following_post_username = list(Connections.objects.filter(followed_by=request.user.username))
    posts_list = []
    for i in range(len(following_post_username)):
        usernames = following_post_username[i].username
        follow_posts = list(Posts.objects.filter(username=usernames))
        for j in range(len(follow_posts)):
            posts_list.append(follow_posts[j])
    return render(request, 'network/following.html', {
        "following_posts": posts_list
    })

@csp_exempt
@login_required(login_url='/login')
def like(request):
    pass


@csp_exempt
@login_required(login_url='/login')
def unlike(request):
    pass

network/templates/network/following.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    <h1>Following</h1>
    <br>
    <div id="posts">
        {% for posts in following_posts %}
        <div class="allposts_wrap">
            <div class="allposts">
                <h5><a href="{% url 'network:profile' posts.username %}">{{ posts.username }}</a></h5>
                <p>{{ posts.timestamp }}</p>
                {% if posts.last_edit %}
                    <p id="p_time {{ posts.id }}"><b>Last Edit:</b> {{ posts.last_edit }}</p>
                {% endif %}
                <p id="content {{ posts.id }}" style="font-size: 18px;">{{ posts.content }}</p>
            </div>
            <br>
        </div>
        {% endfor %}
    </div>
{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block script %}
    <script src="{% static 'network/index.js' %}"></script>
{% endblock %}


{% block body %}
{% load static %}
    <h1>All Posts</h1>
    <br>
    {% if user.is_authenticated %}
    <div id="newpost" class="allposts">
        <h3>New Post</h3>
        <br>
        <form id="postform" method="post">
            {% csrf_token %}
            <textarea cols="100" name="text1" id="text" class="form-control"></textarea>
            <br>
            <input type="submit" class="btn btn-primary" value="Post">
        </form>
    </div>
    <br>
    {% endif %}

    <div id="post_divs">
        {% for post in page_obj %}
        <div class="allposts_wrap">
            <div class="allposts" id="allposts {{ post.id }}">
                <h5><a href="{% url 'network:profile' post.username %}">{{ post.username }}</a></h5>
                <p>{{ post.timestamp }}</p>
                {% if post.last_edit %}
                    <p id="p_time {{ post.id }}"><b>Last Edit:</b> {{ post.last_edit }}</p>
                {% endif %}
                <p id="content {{ post.id }}" style="font-size: 18px;">{{ post.content }}</p>
                {% ifequal post.username user_check %}
                    <a role="button" class="edit_links btn btn-info" id="{{ post.id }}">EDIT</a>
                {% else %}
                <button type="button" class="btn btn-outline-success btn-sm like-unlike" data-like="{{ post.id }}">Like</button>
                {% endifequal %}
            </div>
            <br>
        </div>
       
        {% endfor %}
    </div>
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
            {% endif %}
          {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == page %}
                <li class="page-item disabled"><a aria-disabled="true" class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
          </li>
        </ul>
      </nav>
    
    
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" data-csp-nonce="xyz-123">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
        {% block script %}
        {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'network:index' %}">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
    
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}

{% load static %}
{% block script %}
    <script src="{% static 'network/profile.js' %}"></script>
{% endblock %}

{% block body %}
{% load static %}
<br>
    <div id="profile" class="profile">
        <h1>{{ username }}</h1>
        <br>
        <h5>Following:  {{ following_count }}</h5>
        <h5>Followed By: {{ follower_count }}</h5>
        <br>
        {% if user.is_authenticated %}
        {% ifnotequal username user_check %}
        {% if con_status %}
            <button type="button" class="btn btn-danger" id="unfollow_button" data-tounfollow="{{ username }}">Unfollow</button>
        {% else %}
            <button type="button" class="btn btn-primary" id="follow_button" data-tofollow="{{ username }}">Follow</button>
        {% endif %}
        {% endifnotequal %}
        {% endif %}
    </div>
    <br>
    <div id="post_divs">
        {% for posts in user_posts %}
        <div class="allposts_wrap">
            <div class="allposts" id="allposts {{ posts.id }}">
                <h5><a href="{% url 'network:profile' posts.username %}">{{ posts.username }}</a></h5>
                <p>{{ posts.timestamp }}</p>
                {% if posts.last_edit %}
                    <p id="p_time {{ post.id }}"><b>Last Edit:</b> {{ posts.last_edit }}</p>
                {% endif %}
                <p id="content {{ post.id }}" style="font-size: 18px;">{{ posts.content }}</p>
            </div>
            <br>
        </div>
        {% endfor %}
    </div>
    
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}